name: coburn
channels:
  - pytorch
  - defaults
dependencies:
  - argparse
  - matplotlib
  - pytorch
  - scikit-image
  - scipy
  - torchvision

  - pip:
    - bolt-python
    - boto
    - thunder-python
    - tifffile
    - torch
    - showit
    - keras==2.0.8
    - git+https://github.com/baldassarreFe/pytorch-densenet-tiramisu
