name: coburn
channels:
  - pytorch
  - defaults
dependencies:
  - argparse
  - matplotlib
  - pytorch
  - scikit-image
  - scipy
  - torchvision

  - pip:
    - bolt-python
    - boto
    - thunder-python
    - tifffile
    - torch
    - showit
    - pytorch-fft
