name: coburn
channels:
  - defaults
dependencies:
  - numpy=1.14.2
  - openssl=1.0.2n
  - pandas=0.22.0
  - pip=9.0.1
  - python=3.6.4
  - python-dateutil=2.7.0
  - pytz=2018.3
  - readline=7.0
  - scipy=1.0.0
  - setuptools=38.5.1
  - six=1.11.0
  - sqlite=3.22.0
  - tk=8.6.7
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
