name: coburn
channels:
  - pytorch
  - defaults
dependencies:
  - numpy
  - pandas
  - python=3.6
  - scikit-image
  - scipy
  - pytorch
  - torchvision
  - pip:
    - thunder-python
    - torch
    - showit

